### PR TITLE
Update CheckTx; improvements to the SDK and the CLI

### PR DESCRIPTION
**Pull request by larry0x**
Closes: #73

### CODE REVIEW

**Comment by larry0x** [comment]
Currently, in `CheckTx` we simulate the entire transaction, not just the authentication part. 

This means 1) bigger load on the nodes, and 2) txs that would fail simply won't enter the mempool.

Need to think about whether this is a desired design.

**Comment by Rhaki** [comment]
A transition that fails during the simulation (in this case in the check tx) does not imply that it will also fail during the block insertion. For example, an arbitrage action (which takes into account the txes already in the mempool) could fail in the check tx, but not during the finalize block. Furthermore, if the signature is also verified, there cannot be more than one tx per account in the mempool, as they would have to have two different sequences, and the check tx in the second one would fail because the sequence is not updated

**Comment by Rhaki** [comment]
The second problem could be solved using unordered tx, but it is still a big limitation not being able to have two txes in mempool from the same sender

**Comment by larry0x** [comment]
> A transition that fails during the simulation (in this case in the check tx) does not imply that it will also fail during the block insertion.

True. The converse is also true - succeeding in simulation but can also fail in block.

**Comment by larry0x** [comment]
> if the signature is also verified, there cannot be more than one tx per account in the mempool

Also true, unless we implement ADR-070

**Comment by larry0x** [comment]
Now we only do the authentication part (`before_tx`) in `CheckTx`, instead of the full tx.

**Comment by Rhaki** [comment]
> Now we only do the authentication part (`before_tx`) in `CheckTx`, instead of the full tx.

Consider to add a Query/dedicated entry point on account type contracts for check_tx. This would allow to verify the sign with a sequence that is different from the +1 of the one saved, allowing to have in the mempool multiple txs from the same sender. See [75](https://github.com/left-curve/grug/issues/75)

**Comment by larry0x** [comment]
> allowing to have in the mempool multiple txs from the same sender

For that I think we just implement ADR-070

**Pull request merged**
